### ISSUE TITLE
Syntax smoothing

### ISSUE THREAD

**Issue by jurajHasik** [yastn/yastn#33]
* Initializing operators:
Typically, I create a ``yastn.config`` and then initialize operators based on the same config. Say, spinless fermions, i.e. 

```
import yastn as yastn

config = yastn.make_config(fermionic=True, sym="Z2")
```

It would be straightforward (and desirable) to initialize yastn.operators.SpinlessFermions based on the same config, for example as
``` 
sf= yastn.operators.SpinlessFermions(**config._asdict())
```
This currently doesn't go through since SpinlessFermions expect ``str`` valued ``sym`` argument. Instead, config already contains symmetry object.

**Comment by marekrams** [comment]
This can be done. 
`make_config` understands a few predefined symmetries as strings, so we can reuse sym.SYM_ID to select the proper set of predefined operators.

However, we still have a small inconsistency in naming: 
`U1` e.q. in `config=yastn.make_config(fermionic=True, sym="U1")`
gives config.sym.SYM_ID == "U(1)".  
It would be good to make it consistent. Any preference which way?
